site_name: 我的个人博客
nav:
  - 首页: index.md
  - 第一篇博客: first-post.md

theme:
  name: material
  palette:
    # 日间浅色模式
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: 切换暗色
    # 夜间深色模式
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换亮色
  features:
    - navigation.top
    - content.code.copy
